module.exports = [
    { id: 1, ad: "Single Espresso", fiyat: 65, resim: "/img/singleespresso.jpg", kategori: "espresso" },
    { id: 2, ad: "Double Espresso", fiyat: 90, resim: "/img/doubleespresso.jpg", kategori: "espresso" },
    { id: 3, ad: "Espresso Macchiato", fiyat: 110, resim: "/img/macchiato.jpg", kategori: "espresso" },
    { id: 4, ad: "Double Esp. Macchiato", fiyat: 130, resim: "/img/doublemacchiato.jpg", kategori: "espresso" },
    { id: 5, ad: "Filtre Kahve", fiyat: 120, resim: "/img/filtrekahve.jpg", kategori: "espresso" },
    { id: 6, ad: "Sütlü Filtre Kahve", fiyat: 150, resim: "/img/sütlüfiltre.jpg", kategori: "espresso" },
    { id: 7, ad: "Americano", fiyat: 120, resim: "/img/americano.jpg", kategori: "espresso" },
    { id: 8, ad: "Sütlü Americano", fiyat: 150, resim: "/img/sütlüamericano.jpg", kategori: "espresso" },
    { id: 9, ad: "Cortado", fiyat: 125, resim: "/img/cortado.jpg", kategori: "espresso" },
    { id: 10, ad: "Flat White", fiyat: 140, resim: "/img/flatwhite.jpg", kategori: "espresso" },
    { id: 11, ad: "Cappuccino", fiyat: 150, resim: "/img/cappucino.jpg", kategori: "espresso" },
    { id: 12, ad: "Mocha", fiyat: 150, resim: "/img/mocha.jpg", kategori: "espresso" },
    { id: 13, ad: "White Mocha", fiyat: 150, resim: "/img/whitemocha.jpg", kategori: "espresso" },
    { id: 14, ad: "Latte", fiyat: 150, resim: "/img/latte.jpg", kategori: "espresso" },
    { id: 15, ad: "Caramel Latte", fiyat: 170, resim: "/img/caramellatte.jpg", kategori: "espresso" },
    { id: 16, ad: "Salted Caramel Latte", fiyat: 170, resim: "/img/saltedcaramel.jpg", kategori: "espresso" },
    { id: 17, ad: "Vanilla Latte", fiyat: 170, resim: "/img/vanilya.jpg", kategori: "espresso" },
    { id: 18, ad: "Coconut Latte", fiyat: 170, resim: "/img/coconutlatte.jpg", kategori: "espresso" },
    { id: 19, ad: "Hazelnut Latte", fiyat: 170, resim: "/img/hazelnut.jpg", kategori: "espresso" },
    { id: 20, ad: "Toffee Nut Latte", fiyat: 170, resim: "/img/toffeenut.jpg", kategori: "espresso" },
    { id: 21, ad: "Irish Cream Latte", fiyat: 170, resim: "/img/irishcream.jpg", kategori: "espresso" },
    { id: 22, ad: "Mint Latte", fiyat: 170, resim: "/img/mint.jpg", kategori: "espresso" },
    { id: 23, ad: "Pumpkin Spice Latte", fiyat: 170, resim: "/img/pumpkinlatte.jpg", kategori: "espresso" },
    { id: 24, ad: "Gingerbread Latte", fiyat: 170, resim: "/img/gingerbread.jpg", kategori: "espresso" },

    { id: 100, ad: "Hot Matcha Latte", fiyat: 170, resim: "/img/matcha.jpg", kategori: "matcha" },
    { id: 101, ad: "Ice Matcha", fiyat: 200, resim: "/img/matchacoconut.jpg", kategori: "matcha" },
    { id: 102, ad: "Ice Matcha Çilek", fiyat: 220, resim: "/img/matchacilek.jpg", kategori: "matcha" },
    { id: 103, ad: "Ice Matcha Karadut", fiyat: 220, resim: "/img/matchakaradut.png", kategori: "matcha" },
    { id: 104, ad: "Ice Matcha Mango", fiyat: 220, resim: "/img/matchamango.jpg", kategori: "matcha" },
    { id: 105, ad: "Ice Matcha Vanilya", fiyat: 220, resim: "/img/matchavanilya.jpg", kategori: "matcha" },
    { id: 106, ad: "Ice Matcha Şeftali", fiyat: 220, resim: "/img/matchaşeftali.jpg", kategori: "matcha" },
    { id: 107, ad: "Ice Matcha Kavun", fiyat: 220, resim: "/img/matchakavun.jpg", kategori: "matcha" },

    { id: 200, ad: "Su (330ml)", fiyat: 25, resim: "/img/su.jpg", kategori: "mesrubat" },
    { id: 201, ad: "Sade Soda", fiyat: 35, resim: "/img/soda.jpg", kategori: "mesrubat" },
    { id: 202, ad: "Churchill", fiyat: 75, resim: "/img/churchill.png", kategori: "mesrubat" },
    { id: 203, ad: "Portakal Suyu", fiyat: 90, resim: "/img/portakalsuyu.png", kategori: "mesrubat" },
    { id: 204, ad: "Red Bull Classic", fiyat: 90, resim: "/img/redbull.jpg", kategori: "mesrubat" },
    { id: 205, ad: "Red Bull Blue", fiyat: 90, resim: "/img/redbull_blue.jpg", kategori: "mesrubat" },
    { id: 206, ad: "Red Bull Pink", fiyat: 90, resim: "/img/redbull_pink.jpg", kategori: "mesrubat" },
    { id: 207, ad: "Red Bull White", fiyat: 90, resim: "/img/redbull_white.jpg", kategori: "mesrubat" },
    { id: 208, ad: "Coca Cola", fiyat: 60, resim: "/img/cocacola.jpg", kategori: "mesrubat" },
    { id: 209, ad: "Coca Cola Zero", fiyat: 60, resim: "/img/colazero.png", kategori: "mesrubat" },
    { id: 210, ad: "Sprite", fiyat: 60, resim: "/img/sprite.jpg", kategori: "mesrubat" },
    { id: 211, ad: "Fanta", fiyat: 60, resim: "/img/fanta.png", kategori: "mesrubat" },

    { id: 300, ad: "Martini Mocktail", fiyat: 180, resim: "/img/martinimoctail.jpg", kategori: "mocktail" },
    { id: 301, ad: "Cool Lime", fiyat: 150, resim: "/img/coollime.jpg", kategori: "mocktail" },
    { id: 302, ad: "Borovnica", fiyat: 150, resim: "/img/Borovnica.jpg", kategori: "mocktail" },
    { id: 303, ad: "Hibiscus (Soğuk)", fiyat: 150, resim: "/img/hibiscus.jpg", kategori: "mocktail" },
    { id: 304, ad: "Virgin Mojito", fiyat: 180, resim: "/img/mojito.jpg", kategori: "mocktail" },
    { id: 305, ad: "Blue Lagoon", fiyat: 180, resim: "/img/bluelagoon.jpg", kategori: "mocktail" },
    { id: 306, ad: "Sweet Sunrise", fiyat: 180, resim: "/img/sunrise.jpg", kategori: "mocktail" },
    { id: 307, ad: "Virgin Piña Colada", fiyat: 180, resim: "/img/pinacolada.jpg", kategori: "mocktail" },
    { id: 308, ad: "Virgin Margarita", fiyat: 180, resim: "/img/margarita.jpg", kategori: "mocktail" },
    { id: 309, ad: "Virgin Negroni", fiyat: 180, resim: "/img/negroni.jpg", kategori: "mocktail" },
    { id: 310, ad: "Apple Sour", fiyat: 180, resim: "/img/applesour.jpg", kategori: "mocktail" },
    { id: 311, ad: "Passion Fruit Martini", fiyat: 180, resim: "/img/passionfruitmartini.jpg", kategori: "mocktail" },

    { id: 400, ad: "Sade Poğaça", fiyat: 35, resim: "/img/sadepoca.jpg", kategori: "atistirmalik" },
    { id: 401, ad: "Ev Açması", fiyat: 45, resim: "/img/evaçması.jpg", kategori: "atistirmalik" },
    { id: 402, ad: "Labneli Poğaça", fiyat: 45, resim: "/img/labnelipoca.jpg", kategori: "atistirmalik" },
    { id: 403, ad: "Scone", fiyat: 55, resim: "/img/skone.jpg", kategori: "atistirmalik" },
    { id: 404, ad: "Sade Tereyağlı Kruvasan", fiyat: 95, resim: "/img/kruvasan.jpg", kategori: "atistirmalik" },
    { id: 405, ad: "Pesto Soslu Kruvasan", fiyat: 150, resim: "/img/pestososlukruvasan.jpg", kategori: "atistirmalik" },
    { id: 406, ad: "Dana Füme Kruvasan", fiyat: 150, resim: "/img/domatesdanafümekruvasan.jpg", kategori: "atistirmalik" },
    { id: 407, ad: "Hindi Füme Kruvasan", fiyat: 150, resim: "/img/labnehindifümekruvasan.jpg", kategori: "atistirmalik" },
    { id: 408, ad: "Dana Bacon Sandviç", fiyat: 175, resim: "/img/danabacon.webp", kategori: "atistirmalik" },
    { id: 409, ad: "Dana Macar Salam", fiyat: 175, resim: "/img/danamacarsalam.webp", kategori: "atistirmalik" },
    { id: 410, ad: "Dana Jambon Sandviç", fiyat: 175, resim: "/img/danajambon.webp", kategori: "atistirmalik" },
    { id: 411, ad: "Hindi Füme Sandviç", fiyat: 175, resim: "/img/hindifümeli.webp", kategori: "atistirmalik" },
    { id: 412, ad: "Pastırmalı Sandviç", fiyat: 175, resim: "/img/pastırmalım.webp", kategori: "atistirmalik" },
    { id: 413, ad: "Çeçil Peynirli Sandviç", fiyat: 175, resim: "/img/çeçilpeynirli.webp", kategori: "atistirmalik" },
    { id: 414, ad: "Beyaz Peynirli Sandviç", fiyat: 175, resim: "/img/beyazpeynirli.webp", kategori: "atistirmalik" },
    { id: 415, ad: "Kaşarlı Sandviç", fiyat: 175, resim: "/img/kasarlı.webp", kategori: "atistirmalik" },

    { id: 500, ad: "Çay", fiyat: 35, resim: "/img/cay.jpg", kategori: "sicak_icecek" },
    { id: 501, ad: "Fincan Çay", fiyat: 50, resim: "/img/fincancay.jpg", kategori: "sicak_icecek" },
    { id: 502, ad: "Türk Kahvesi", fiyat: 75, resim: "/img/tk.jpg", kategori: "sicak_icecek" },
    { id: 503, ad: "Double Türk Kahvesi", fiyat: 100, resim: "/img/doubletk.jpg", kategori: "sicak_icecek" },
    { id: 504, ad: "Salep", fiyat: 140, resim: "/img/salep.jpg", kategori: "sicak_icecek" },
    { id: 505, ad: "Sıcak Çikolata", fiyat: 140, resim: "/img/sicakcikolata.jpg", kategori: "sicak_icecek" },
    { id: 506, ad: "Beyaz Sıcak Çikolata", fiyat: 100, resim: "/img/beyazcikolata.jpg", kategori: "sicak_icecek" },
    { id: 507, ad: "Ihlamur", fiyat: 100, resim: "/img/ihlamur.jpg", kategori: "sicak_icecek" },
    { id: 508, ad: "Rezene Çayı", fiyat: 100, resim: "/img/rezene.jpg", kategori: "sicak_icecek" },
    { id: 509, ad: "Kış Çayı", fiyat: 100, resim: "/img/kışçayı.jpg", kategori: "sicak_icecek" },
    { id: 510, ad: "Nane Limon", fiyat: 100, resim: "/img/nanelimon.png", kategori: "sicak_icecek" },
    { id: 511, ad: "Hibiscus Çayı", fiyat: 100, resim: "/img/hibiscus.png", kategori: "sicak_icecek" },
    { id: 512, ad: "Yeşilçay", fiyat: 100, resim: "/img/yesilcay.jpg", kategori: "sicak_icecek" },
    { id: 513, ad: "Kuşburnu Çayı", fiyat: 100, resim: "/img/kuşburnu.jpg", kategori: "sicak_icecek" },
    { id: 514, ad: "Melisa Çayı", fiyat: 100, resim: "/img/melisa.jpg", kategori: "sicak_icecek" },
    { id: 515, ad: "Papatya Çayı", fiyat: 100, resim: "/img/papatya.png", kategori: "sicak_icecek" },

    { id: 600, ad: "Iced Double Espresso", fiyat: 100, resim: "/img/icedoubleespresso.jpg", kategori: "soguk_kahve" },
    { id: 601, ad: "Iced Filtre", fiyat: 120, resim: "/img/icefiltre.jpg", kategori: "soguk_kahve" },
    { id: 602, ad: "Iced Americano", fiyat: 120, resim: "/img/iceamericano.jpg", kategori: "soguk_kahve" },
    { id: 603, ad: "Sütlü Iced Americano", fiyat: 150, resim: "/img/sütlüiceamericano.jpg", kategori: "soguk_kahve" },
    { id: 604, ad: "Iced Cappucino", fiyat: 150, resim: "/img/icecappucino.jpg", kategori: "soguk_kahve" },
    { id: 605, ad: "Iced Mocha", fiyat: 150, resim: "/img/icemocha.png", kategori: "soguk_kahve" },
    { id: 606, ad: "Iced White Mocha", fiyat: 150, resim: "/img/icewhitemocha.jpg", kategori: "soguk_kahve" },
    { id: 607, ad: "Iced Latte", fiyat: 150, resim: "/img/icelatte.jpg", kategori: "soguk_kahve" },
    { id: 608, ad: "Iced Caramel Latte", fiyat: 170, resim: "/img/icecaramel.jpg", kategori: "soguk_kahve" },
    { id: 609, ad: "Iced Salted Caramel", fiyat: 170, resim: "/img/icesaltedcaramel.jpg", kategori: "soguk_kahve" },
    { id: 610, ad: "Iced Vanilla Latte", fiyat: 170, resim: "/img/icevanilla.jpg", kategori: "soguk_kahve" },
    { id: 611, ad: "Iced Coconut Latte", fiyat: 170, resim: "/img/icecoconut.jpg", kategori: "soguk_kahve" },
    { id: 612, ad: "Iced Hazelnut Latte", fiyat: 170, resim: "/img/icehazelnut.jpg", kategori: "soguk_kahve" },
    { id: 613, ad: "Iced Toffee Nut Latte", fiyat: 170, resim: "/img/icetoffee.jpg", kategori: "soguk_kahve" },
    { id: 614, ad: "Iced Irish Cream Latte", fiyat: 170, resim: "/img/iceirishcream.jpg", kategori: "soguk_kahve" },
    { id: 615, ad: "Iced Mint Latte", fiyat: 170, resim: "/img/icemint.jpg", kategori: "soguk_kahve" },
    { id: 616, ad: "Iced Pumpkin Latte", fiyat: 170, resim: "/img/icepumpkin.jpg", kategori: "soguk_kahve" },
    { id: 617, ad: "Iced Gingerbread Latte", fiyat: 170, resim: "/img/icegingerbread.jpg", kategori: "soguk_kahve" },
    { id: 618, ad: "Affogato", fiyat: 160, resim: "/img/affogato.jpg", kategori: "soguk_kahve" },
    { id: 619, ad: "Çikolatalı Affogato", fiyat: 180, resim: "/img/cikolatalıaffogato.jpg", kategori: "soguk_kahve" },

    { id: 700, ad: "Klasik Cookie", fiyat: 120, resim: "/img/cookie.jpg.webp", kategori: "tatli" },
    { id: 701, ad: "Lotus Cookie", fiyat: 120, resim: "/img/lotuscookie.webp", kategori: "tatli" },
    { id: 702, ad: "Rafaello Cookie", fiyat: 120, resim: "/img/rafaellocookie.webp", kategori: "tatli" },
    { id: 703, ad: "Karamelli Cookie", fiyat: 120, resim: "/img/karamellicookie..webp", kategori: "tatli" },
    { id: 704, ad: "Bademli Brownie", fiyat: 150, resim: "/img/bademlibrownie.webp", kategori: "tatli" },
    { id: 705, ad: "Mud Cake", fiyat: 150, resim: "/img/mudkek.webp", kategori: "tatli" },
    { id: 706, ad: "Dubai Cookie", fiyat: 180, resim: "/img/dubaicookie.webp", kategori: "tatli" },
    { id: 707, ad: "Dubai Çikolatası (Dilim)", fiyat: 180, resim: "/img/dubaicikolatasi.webp", kategori: "tatli" },
    { id: 708, ad: "San Sebastian (Sade)", fiyat: 180, resim: "/img/sansebastian.webp", kategori: "tatli" },
    { id: 709, ad: "Nutellalı San Sebastian", fiyat: 200, resim: "/img/nutellasansebastian.webp", kategori: "tatli" },
    { id: 710, ad: "Orman Meyveli San Sebastian", fiyat: 200, resim: "/img/ormanmeyvelisansebo.webp", kategori: "tatli" },
    { id: 711, ad: "Muzlu Karamelli San Sebastian", fiyat: 200, resim: "/img/sansebastiann.webp", kategori: "tatli" },
    { id: 712, ad: "Kahveli Pasta", fiyat: 200, resim: "/img/coffeepasta.webp", kategori: "tatli" },
    { id: 713, ad: "Yaban Mersinli Pasta", fiyat: 250, resim: "/img/blueberrypasta.webp", kategori: "tatli" },
    { id: 714, ad: "Fıstıklı Pasta", fiyat: 250, resim: "/img/fıstıkpasta.webp", kategori: "tatli" },
    { id: 715, ad: "Portakallı Pasta", fiyat: 250, resim: "/img/portakapasta.webp", kategori: "tatli" },
    { id: 716, ad: "Tiramisu", fiyat: 200, resim: "/img/tiramisu.jpg", kategori: "tatli" },
    { id: 717, ad: "Limonlu Cheesecake", fiyat: 200, resim: "/img/limonlucheesecake.jpg", kategori: "tatli" },
    { id: 718, ad: "Frambuazlı Cheesecake", fiyat: 200, resim: "/img/frambuazlıcheesecake.jpg", kategori: "tatli" },
    { id: 719, ad: "Oreolu Cheesecake", fiyat: 200, resim: "/img/oreolucheesecake.jpg", kategori: "tatli" },
    { id: 720, ad: "Klasik Brownie", fiyat: 200, resim: "/img/brownie.webp", kategori: "tatli" },
    { id: 721, ad: "Vişneli Brownie", fiyat: 200, resim: "/img/visnelibrownie.webp", kategori: "tatli" },
    { id: 722, ad: "Supangle", fiyat: 200, resim: "/img/supangle.jpg", kategori: "tatli" },
    { id: 723, ad: "Profiterol", fiyat: 200, resim: "/img/profiterol.jpg", kategori: "tatli" },
    { id: 724, ad: "Çikolatalı Cup", fiyat: 200, resim: "/img/cikolatalıcup.webp", kategori: "tatli" },
    { id: 725, ad: "Nutellalı Muzlu Mag", fiyat: 210, resim: "/img/nutellalımuzlumag.webp", kategori: "tatli" },
    { id: 726, ad: "Muzlu Magnolia", fiyat: 210, resim: "/img/muzlumag.jpg", kategori: "tatli" },
    { id: 727, ad: "Oreolu Magnolia", fiyat: 210, resim: "/img/oreolumag.jpg", kategori: "tatli" },
    { id: 728, ad: "Havuçlu Cup", fiyat: 210, resim: "/img/carrotcup.webp", kategori: "tatli" },
    { id: 729, ad: "Lotuslu Magnolia", fiyat: 210, resim: "/img/lotuslumag.jpg", kategori: "tatli" },
    { id: 730, ad: "Frambuazlı Magnolia", fiyat: 210, resim: "/img/frambuazlımag.jpg", kategori: "tatli" },
    { id: 731, ad: "Orman Meyveli Magnolia", fiyat: 210, resim: "/img/ormanmeyvelimag.jpg", kategori: "tatli" },
    { id: 801, ad: "Ev Yapımı Limonata", fiyat: 120, resim: "/img/limonata.jpg", kategori: "soguk_special", tip: "frozen" },
    { id: 802, ad: "Çilekli Limonata", fiyat: 120, resim: "/img/cileklilimonata.jpg", kategori: "soguk_special", tip: "frozen" },
    { id: 803, ad: "Şeftali Soğuk Çay", fiyat: 120, resim: "/img/seftalilisogukcay.png", kategori: "soguk_special", tip: "frozen" },
    { id: 804, ad: "Mangolu Soğuk Çay", fiyat: 120, resim: "/img/mangolusogukcay.png", kategori: "soguk_special", tip: "frozen" },
    { id: 805, ad: "Çilekli Frozen", fiyat: 150, resim: "/img/çileklifrozen.jpg", kategori: "soguk_special", tip: "frozen" },
    { id: 806, ad: "Orman M. Frozen", fiyat: 150, resim: "/img/ormanfrozen.jpg", kategori: "soguk_special", tip: "frozen" },
    { id: 807, ad: "Mangolu Frozen", fiyat: 150, resim: "/img/mangolufrozen.jpg", kategori: "soguk_special", tip: "frozen" },
    { id: 808, ad: "Muzlu Frozen", fiyat: 150, resim: "/img/muzlufrozen.jpg", kategori: "soguk_special", tip: "frozen" },
    { id: 809, ad: "Çikolatalı Milkshake", fiyat: 160, resim: "/img/cikolatalimilkshake.jpg", kategori: "soguk_special", tip: "tekboy" },
    { id: 810, ad: "Çilekli Milkshake", fiyat: 160, resim: "/img/cileklimilkshake.jpg", kategori: "soguk_special", tip: "tekboy" },
    { id: 811, ad: "Karamelli Milkshake", fiyat: 160, resim: "/img/karamellimilkshake.jpg", kategori: "soguk_special", tip: "tekboy" },
    { id: 812, ad: "Vanilyalı Milkshake", fiyat: 160, resim: "/img/vanilyalımilkshake.jpg", kategori: "soguk_special", tip: "tekboy" },
    { id: 813, ad: "Çikolatalı Frappe", fiyat: 160, resim: "/img/cikolatalıfrap.jpg", kategori: "soguk_special", tip: "tekboy" },
    { id: 814, ad: "Karamelli Frappe", fiyat: 160, resim: "/img/karamellifrappucino.jpg", kategori: "soguk_special", tip: "tekboy" },
    { id: 815, ad: "Cookie Frappe", fiyat: 160, resim: "/img/cookiefrappucino.jpg", kategori: "soguk_special", tip: "tekboy" },
    { id: 816, ad: "Toffee Nut Frappe", fiyat: 160, resim: "/img/toffeenutfrappe.jpg", kategori: "soguk_special", tip: "tekboy" }
];